apiVersion: 1

datasources:
  - name: Prometheus (Archestra)
    type: prometheus
    access: proxy
    url: http://archestra:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 5s
      queryTimeout: 60s
