apiVersion: 1

datasources:
  - name: Prometheus (Archestra)
    type: prometheus
    access: proxy
    url: http://archestra:9090
    isDefault: false
    editable: true
    jsonData:
      timeInterval: 5s
      queryTimeout: 60s

  - name: SecureOps Database
    type: postgres
    access: proxy
    url: ${GRAFANA_DB_HOST}:5432
    database: ${GRAFANA_DB_NAME}
    user: ${GRAFANA_DB_USER}
    isDefault: true
    editable: true
    secureJsonData:
      password: ${GRAFANA_DB_PASSWORD}
    jsonData:
      sslmode: require
      postgresVersion: 1500
      timescaledb: false
